// This file has been generated by Py++.

#ifndef AlignmentFormatBlocks_hpp__pyplusplus_wrapper
#define AlignmentFormatBlocks_hpp__pyplusplus_wrapper

void register_AlignmentFormatBlocks_class();

#endif//AlignmentFormatBlocks_hpp__pyplusplus_wrapper
