// This file has been generated by Py++.

#ifndef AlignmentFormatEmissions_hpp__pyplusplus_wrapper
#define AlignmentFormatEmissions_hpp__pyplusplus_wrapper

void register_AlignmentFormatEmissions_class();

#endif//AlignmentFormatEmissions_hpp__pyplusplus_wrapper
