// This file has been generated by Py++.

#include "boost/python.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "AlignlibBase.pypp.hpp"

namespace bp = boost::python;

void register_AlignlibBase_class(){

    { //::alignlib::AlignlibBase
        typedef bp::class_< alignlib::AlignlibBase > AlignlibBase_exposer_t;
        AlignlibBase_exposer_t AlignlibBase_exposer = AlignlibBase_exposer_t( "AlignlibBase" );
        bp::scope AlignlibBase_scope( AlignlibBase_exposer );
    }

}
