// This file has been generated by Py++.

#ifndef AlignmentFormatBlat_hpp__pyplusplus_wrapper
#define AlignmentFormatBlat_hpp__pyplusplus_wrapper

void register_AlignmentFormatBlat_class();

#endif//AlignmentFormatBlat_hpp__pyplusplus_wrapper
