// This file has been generated by Py++.

#ifndef AlignlibBase_hpp__pyplusplus_wrapper
#define AlignlibBase_hpp__pyplusplus_wrapper

void register_AlignlibBase_class();

#endif//AlignlibBase_hpp__pyplusplus_wrapper
