// This file has been generated by Py++.

#ifndef AlignmentFormatExplicit_hpp__pyplusplus_wrapper
#define AlignmentFormatExplicit_hpp__pyplusplus_wrapper

void register_AlignmentFormatExplicit_class();

#endif//AlignmentFormatExplicit_hpp__pyplusplus_wrapper
