// This file has been generated by Py++.

#ifndef Alignator_hpp__pyplusplus_wrapper
#define Alignator_hpp__pyplusplus_wrapper

void register_Alignator_class();

#endif//Alignator_hpp__pyplusplus_wrapper
