// This file has been generated by Py++.

#ifndef AlignmentFormatDiagonals_hpp__pyplusplus_wrapper
#define AlignmentFormatDiagonals_hpp__pyplusplus_wrapper

void register_AlignmentFormatDiagonals_class();

#endif//AlignmentFormatDiagonals_hpp__pyplusplus_wrapper
