// This file has been generated by Py++.

#ifndef alignlib_free_functions_hpp__pyplusplus_wrapper
#define alignlib_free_functions_hpp__pyplusplus_wrapper

void register_free_functions();

#endif//alignlib_free_functions_hpp__pyplusplus_wrapper
