// This file has been generated by Py++.

#ifndef AlignatumVector_hpp__pyplusplus_wrapper
#define AlignatumVector_hpp__pyplusplus_wrapper

void register_AlignatumVector_class();

#endif//AlignatumVector_hpp__pyplusplus_wrapper
