// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "AlignatumVector.pypp.hpp"

namespace bp = boost::python;

void register_AlignatumVector_class(){

    { //::std::vector< boost::shared_ptr<alignlib::Alignatum> >
        typedef bp::class_< std::vector< boost::shared_ptr<alignlib::Alignatum> > > AlignatumVector_exposer_t;
        AlignatumVector_exposer_t AlignatumVector_exposer = AlignatumVector_exposer_t( "AlignatumVector" );
        bp::scope AlignatumVector_scope( AlignatumVector_exposer );
        AlignatumVector_exposer.def( bp::vector_indexing_suite< ::std::vector< boost::shared_ptr<alignlib::Alignatum> >, true >() );
    }

}
