// This file has been generated by Py++.

#ifndef calignlib_enumerations_hpp__pyplusplus_wrapper
#define calignlib_enumerations_hpp__pyplusplus_wrapper

void register_enumerations();

#endif//calignlib_enumerations_hpp__pyplusplus_wrapper
