// This file has been generated by Py++.

#ifndef calignlib_free_functions_hpp__pyplusplus_wrapper
#define calignlib_free_functions_hpp__pyplusplus_wrapper

void register_free_functions();

#endif//calignlib_free_functions_hpp__pyplusplus_wrapper
