// This file has been generated by Py++.

#ifndef Coordinate_hpp__pyplusplus_wrapper
#define Coordinate_hpp__pyplusplus_wrapper

void register_Coordinate_class();

#endif//Coordinate_hpp__pyplusplus_wrapper
