// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "CountVector.pypp.hpp"

namespace bp = boost::python;

void register_CountVector_class(){

    { //::std::vector< unsigned int >
        typedef bp::class_< std::vector< unsigned int > > CountVector_exposer_t;
        CountVector_exposer_t CountVector_exposer = CountVector_exposer_t( "CountVector" );
        bp::scope CountVector_scope( CountVector_exposer );
        CountVector_exposer.def( bp::vector_indexing_suite< ::std::vector< unsigned int >, true >() );
    }

}
