// This file has been generated by Py++.

#ifndef CountVector_hpp__pyplusplus_wrapper
#define CountVector_hpp__pyplusplus_wrapper

void register_CountVector_class();

#endif//CountVector_hpp__pyplusplus_wrapper
