// This file has been generated by Py++.

#ifndef MatrixDouble_hpp__pyplusplus_wrapper
#define MatrixDouble_hpp__pyplusplus_wrapper

void register_MatrixDouble_class();

#endif//MatrixDouble_hpp__pyplusplus_wrapper
