// This file has been generated by Py++.

#include "boost/python.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "MatrixInt.pypp.hpp"

namespace bp = boost::python;

void register_MatrixInt_class(){

    { //::alignlib::Matrix< int >
        typedef bp::class_< alignlib::Matrix< int > > MatrixInt_exposer_t;
        MatrixInt_exposer_t MatrixInt_exposer = MatrixInt_exposer_t( "MatrixInt", bp::init< unsigned int, unsigned int, bp::optional< int > >(( bp::arg("r"), bp::arg("c"), bp::arg("default_value")=(int)(0) )) );
        bp::scope MatrixInt_scope( MatrixInt_exposer );
        MatrixInt_exposer.def( bp::init< alignlib::Matrix< int > const & >(( bp::arg("src") )) );
        { //::alignlib::Matrix< int >::addValue
        
            typedef alignlib::Matrix< int > exported_class_t;
            typedef void ( exported_class_t::*addValue_function_type )( unsigned int,unsigned int,int const & ) ;
            
            MatrixInt_exposer.def( 
                "addValue"
                , addValue_function_type( &::alignlib::Matrix< int >::addValue )
                , ( bp::arg("row"), bp::arg("col"), bp::arg("value") ) );
        
        }
        { //::alignlib::Matrix< int >::getClone
        
            typedef alignlib::Matrix< int > exported_class_t;
            typedef ::boost::shared_ptr< alignlib::Matrix< int > > ( exported_class_t::*getClone_function_type )(  ) const;
            
            MatrixInt_exposer.def( 
                "getClone"
                , getClone_function_type( &::alignlib::Matrix< int >::getClone ) );
        
        }
        { //::alignlib::Matrix< int >::getNew
        
            typedef alignlib::Matrix< int > exported_class_t;
            typedef ::boost::shared_ptr< alignlib::Matrix< int > > ( exported_class_t::*getNew_function_type )(  ) const;
            
            MatrixInt_exposer.def( 
                "getNew"
                , getNew_function_type( &::alignlib::Matrix< int >::getNew ) );
        
        }
        { //::alignlib::Matrix< int >::getNumCols
        
            typedef alignlib::Matrix< int > exported_class_t;
            typedef unsigned int ( exported_class_t::*getNumCols_function_type )(  ) const;
            
            MatrixInt_exposer.def( 
                "getNumCols"
                , getNumCols_function_type( &::alignlib::Matrix< int >::getNumCols ) );
        
        }
        { //::alignlib::Matrix< int >::getNumRows
        
            typedef alignlib::Matrix< int > exported_class_t;
            typedef unsigned int ( exported_class_t::*getNumRows_function_type )(  ) const;
            
            MatrixInt_exposer.def( 
                "getNumRows"
                , getNumRows_function_type( &::alignlib::Matrix< int >::getNumRows ) );
        
        }
        { //::alignlib::Matrix< int >::getValue
        
            typedef alignlib::Matrix< int > exported_class_t;
            typedef int ( exported_class_t::*getValue_function_type )( unsigned int,unsigned int ) const;
            
            MatrixInt_exposer.def( 
                "getValue"
                , getValue_function_type( &::alignlib::Matrix< int >::getValue )
                , ( bp::arg("row"), bp::arg("col") ) );
        
        }
        { //::alignlib::Matrix< int >::operator=
        
            typedef alignlib::Matrix< int > exported_class_t;
            typedef ::alignlib::Matrix< int > & ( exported_class_t::*assign_function_type )( ::alignlib::Matrix< int > const & ) ;
            
            MatrixInt_exposer.def( 
                "assign"
                , assign_function_type( &::alignlib::Matrix< int >::operator= )
                , ( bp::arg("src") )
                , bp::return_self< >() );
        
        }
        MatrixInt_exposer.def( bp::self == bp::self );
        { //::alignlib::Matrix< int >::setValue
        
            typedef alignlib::Matrix< int > exported_class_t;
            typedef void ( exported_class_t::*setValue_function_type )( unsigned int,unsigned int,int const & ) ;
            
            MatrixInt_exposer.def( 
                "setValue"
                , setValue_function_type( &::alignlib::Matrix< int >::setValue )
                , ( bp::arg("row"), bp::arg("col"), bp::arg("value") ) );
        
        }
        { //::alignlib::Matrix< int >::swapRows
        
            typedef alignlib::Matrix< int > exported_class_t;
            typedef void ( exported_class_t::*swapRows_function_type )( unsigned int,unsigned int ) ;
            
            MatrixInt_exposer.def( 
                "swapRows"
                , swapRows_function_type( &::alignlib::Matrix< int >::swapRows )
                , ( bp::arg("x"), bp::arg("y") ) );
        
        }
        bp::register_ptr_to_python< boost::shared_ptr< alignlib::Matrix<int> > >();
    }

}
