// This file has been generated by Py++.

#include "boost/python.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "MultipleAlignator.pypp.hpp"

namespace bp = boost::python;

void register_MultipleAlignator_class(){

    { //::alignlib::MultipleAlignator
        typedef bp::class_< alignlib::MultipleAlignator, boost::noncopyable > MultipleAlignator_exposer_t;
        MultipleAlignator_exposer_t MultipleAlignator_exposer = MultipleAlignator_exposer_t( "MultipleAlignator", bp::no_init );
        bp::scope MultipleAlignator_scope( MultipleAlignator_exposer );
        { //::alignlib::MultipleAlignator::align
        
            typedef void ( ::alignlib::MultipleAlignator::*align_function_type )( ::alignlib::HMultAlignment &,::alignlib::HAlignandumVector const & ) const;
            
            MultipleAlignator_exposer.def( 
                "align"
                , align_function_type( &::alignlib::MultipleAlignator::align )
                , ( bp::arg("dest"), bp::arg("sequences") ) );
        
        }
        { //::alignlib::MultipleAlignator::align
        
            typedef void ( ::alignlib::MultipleAlignator::*align_function_type )( ::alignlib::HMultAlignment &,::alignlib::HStringVector const & ) const;
            
            MultipleAlignator_exposer.def( 
                "align"
                , align_function_type( &::alignlib::MultipleAlignator::align )
                , ( bp::arg("dest"), bp::arg("sequences") ) );
        
        }
        { //::alignlib::MultipleAlignator::getClone
        
            typedef ::alignlib::HMultipleAlignator ( ::alignlib::MultipleAlignator::*getClone_function_type )(  ) const;
            
            MultipleAlignator_exposer.def( 
                "getClone"
                , getClone_function_type( &::alignlib::MultipleAlignator::getClone ) );
        
        }
        bp::register_ptr_to_python< boost::shared_ptr< alignlib::MultipleAlignator > >();
    }

}
