// This file has been generated by Py++.

#ifndef MultAlignment_hpp__pyplusplus_wrapper
#define MultAlignment_hpp__pyplusplus_wrapper

void register_MultAlignment_class();

#endif//MultAlignment_hpp__pyplusplus_wrapper
