// This file has been generated by Py++.

#ifndef MultAlignmentFormatPlain_hpp__pyplusplus_wrapper
#define MultAlignmentFormatPlain_hpp__pyplusplus_wrapper

void register_MultAlignmentFormatPlain_class();

#endif//MultAlignmentFormatPlain_hpp__pyplusplus_wrapper
