// This file has been generated by Py++.

#ifndef MultipleAlignator_hpp__pyplusplus_wrapper
#define MultipleAlignator_hpp__pyplusplus_wrapper

void register_MultipleAlignator_class();

#endif//MultipleAlignator_hpp__pyplusplus_wrapper
