// This file has been generated by Py++.

#ifndef MultAlignmentFormat_hpp__pyplusplus_wrapper
#define MultAlignmentFormat_hpp__pyplusplus_wrapper

void register_MultAlignmentFormat_class();

#endif//MultAlignmentFormat_hpp__pyplusplus_wrapper
