// This file has been generated by Py++.

#include "boost/python.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "MultAlignmentFormat.pypp.hpp"

namespace bp = boost::python;

struct MultAlignmentFormat_wrapper : alignlib::MultAlignmentFormat, bp::wrapper< alignlib::MultAlignmentFormat > {

    MultAlignmentFormat_wrapper( )
    : alignlib::MultAlignmentFormat( )
      , bp::wrapper< alignlib::MultAlignmentFormat >(){
        // null constructor
    
    }

    MultAlignmentFormat_wrapper(::alignlib::HMultAlignment const & src, ::alignlib::HStringVector const & sequences )
    : alignlib::MultAlignmentFormat( src, sequences )
      , bp::wrapper< alignlib::MultAlignmentFormat >(){
        // constructor
    
    }

    MultAlignmentFormat_wrapper(::std::istream & src )
    : alignlib::MultAlignmentFormat( boost::ref(src) )
      , bp::wrapper< alignlib::MultAlignmentFormat >(){
        // constructor
    
    }

    MultAlignmentFormat_wrapper(::std::string const & src )
    : alignlib::MultAlignmentFormat( src )
      , bp::wrapper< alignlib::MultAlignmentFormat >(){
        // constructor
    
    }

    MultAlignmentFormat_wrapper(::alignlib::MultAlignmentFormat const & arg0 )
    : alignlib::MultAlignmentFormat( boost::ref(arg0) )
      , bp::wrapper< alignlib::MultAlignmentFormat >(){
        // copy constructor
    
    }

    virtual void copy( ::alignlib::HMultAlignment & dest, ::alignlib::HAlignment const & templ ) const  {
        if( bp::override func_copy = this->get_override( "copy" ) )
            func_copy( dest, templ );
        else
            this->alignlib::MultAlignmentFormat::copy( dest, templ );
    }
    
    
    void default_copy( ::alignlib::HMultAlignment & dest, ::alignlib::HAlignment const & templ ) const  {
        alignlib::MultAlignmentFormat::copy( dest, templ );
    }

    virtual void fill( ::alignlib::HMultAlignment const & src, ::alignlib::HStringVector const & sequences ) {
        if( bp::override func_fill = this->get_override( "fill" ) )
            func_fill( src, sequences );
        else
            this->alignlib::MultAlignmentFormat::fill( src, sequences );
    }
    
    
    void default_fill( ::alignlib::HMultAlignment const & src, ::alignlib::HStringVector const & sequences ) {
        alignlib::MultAlignmentFormat::fill( src, sequences );
    }

    virtual void load( ::std::istream & arg0 ) {
        if( bp::override func_load = this->get_override( "load" ) )
            func_load( boost::ref(arg0) );
        else
            this->alignlib::MultAlignmentFormat::load( boost::ref(arg0) );
    }
    
    
    void default_load( ::std::istream & arg0 ) {
        alignlib::MultAlignmentFormat::load( boost::ref(arg0) );
    }

    virtual void save( ::std::ostream & arg0 ) const  {
        if( bp::override func_save = this->get_override( "save" ) )
            func_save( boost::ref(arg0) );
        else
            this->alignlib::MultAlignmentFormat::save( boost::ref(arg0) );
    }
    
    
    void default_save( ::std::ostream & arg0 ) const  {
        alignlib::MultAlignmentFormat::save( boost::ref(arg0) );
    }

};

void register_MultAlignmentFormat_class(){

    { //::alignlib::MultAlignmentFormat
        typedef bp::class_< MultAlignmentFormat_wrapper > MultAlignmentFormat_exposer_t;
        MultAlignmentFormat_exposer_t MultAlignmentFormat_exposer = MultAlignmentFormat_exposer_t( "MultAlignmentFormat", bp::init< >() );
        bp::scope MultAlignmentFormat_scope( MultAlignmentFormat_exposer );
        MultAlignmentFormat_exposer.def( bp::init< alignlib::HMultAlignment const &, alignlib::HStringVector const & >(( bp::arg("src"), bp::arg("sequences") )) );
        MultAlignmentFormat_exposer.def( bp::init< std::istream & >(( bp::arg("src") )) );
        bp::implicitly_convertible< std::istream &, alignlib::MultAlignmentFormat >();
        MultAlignmentFormat_exposer.def( bp::init< std::string const & >(( bp::arg("src") )) );
        bp::implicitly_convertible< std::string const &, alignlib::MultAlignmentFormat >();
        MultAlignmentFormat_exposer.def( bp::init< alignlib::MultAlignmentFormat const & >(( bp::arg("arg0") )) );
        { //::alignlib::MultAlignmentFormat::copy
        
            typedef void ( ::alignlib::MultAlignmentFormat::*copy_function_type )( ::alignlib::HMultAlignment &,::alignlib::HAlignment const & ) const;
            typedef void ( MultAlignmentFormat_wrapper::*default_copy_function_type )( ::alignlib::HMultAlignment &,::alignlib::HAlignment const & ) const;
            
            MultAlignmentFormat_exposer.def( 
                "copy"
                , copy_function_type(&::alignlib::MultAlignmentFormat::copy)
                , default_copy_function_type(&MultAlignmentFormat_wrapper::default_copy)
                , ( bp::arg("dest"), bp::arg("templ") ) );
        
        }
        { //::alignlib::MultAlignmentFormat::fill
        
            typedef void ( ::alignlib::MultAlignmentFormat::*fill_function_type )( ::alignlib::HMultAlignment const &,::alignlib::HStringVector const & ) ;
            typedef void ( MultAlignmentFormat_wrapper::*default_fill_function_type )( ::alignlib::HMultAlignment const &,::alignlib::HStringVector const & ) ;
            
            MultAlignmentFormat_exposer.def( 
                "fill"
                , fill_function_type(&::alignlib::MultAlignmentFormat::fill)
                , default_fill_function_type(&MultAlignmentFormat_wrapper::default_fill)
                , ( bp::arg("src"), bp::arg("sequences") ) );
        
        }
        { //::alignlib::MultAlignmentFormat::load
        
            typedef void ( ::alignlib::MultAlignmentFormat::*load_function_type )( ::std::istream & ) ;
            typedef void ( MultAlignmentFormat_wrapper::*default_load_function_type )( ::std::istream & ) ;
            
            MultAlignmentFormat_exposer.def( 
                "load"
                , load_function_type(&::alignlib::MultAlignmentFormat::load)
                , default_load_function_type(&MultAlignmentFormat_wrapper::default_load)
                , ( bp::arg("arg0") ) );
        
        }
        { //::alignlib::MultAlignmentFormat::save
        
            typedef void ( ::alignlib::MultAlignmentFormat::*save_function_type )( ::std::ostream & ) const;
            typedef void ( MultAlignmentFormat_wrapper::*default_save_function_type )( ::std::ostream & ) const;
            
            MultAlignmentFormat_exposer.def( 
                "save"
                , save_function_type(&::alignlib::MultAlignmentFormat::save)
                , default_save_function_type(&MultAlignmentFormat_wrapper::default_save)
                , ( bp::arg("arg0") ) );
        
        }
        MultAlignmentFormat_exposer.def_readwrite( "mData", &alignlib::MultAlignmentFormat::mData );
        MultAlignmentFormat_exposer.def( bp::self_ns::str( bp::self ) );
    }

}
