// This file has been generated by Py++.

#ifndef NormalDistributionParameters_hpp__pyplusplus_wrapper
#define NormalDistributionParameters_hpp__pyplusplus_wrapper

void register_NormalDistributionParameters_class();

#endif//NormalDistributionParameters_hpp__pyplusplus_wrapper
