// This file has been generated by Py++.

#include "boost/python.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "NormalDistributionParameters.pypp.hpp"

namespace bp = boost::python;

void register_NormalDistributionParameters_class(){

    { //::alignlib::NormalDistributionParameters
        typedef bp::class_< alignlib::NormalDistributionParameters > NormalDistributionParameters_exposer_t;
        NormalDistributionParameters_exposer_t NormalDistributionParameters_exposer = NormalDistributionParameters_exposer_t( "NormalDistributionParameters" );
        bp::scope NormalDistributionParameters_scope( NormalDistributionParameters_exposer );
        { //::alignlib::NormalDistributionParameters::getMean
        
            typedef double ( ::alignlib::NormalDistributionParameters::*getMean_function_type )(  ) ;
            
            NormalDistributionParameters_exposer.def( 
                "getMean"
                , getMean_function_type( &::alignlib::NormalDistributionParameters::getMean ) );
        
        }
        { //::alignlib::NormalDistributionParameters::getStandardDeviation
        
            typedef double ( ::alignlib::NormalDistributionParameters::*getStandardDeviation_function_type )(  ) ;
            
            NormalDistributionParameters_exposer.def( 
                "getStandardDeviation"
                , getStandardDeviation_function_type( &::alignlib::NormalDistributionParameters::getStandardDeviation ) );
        
        }
        NormalDistributionParameters_exposer.def_readwrite( "mMean", &alignlib::NormalDistributionParameters::mMean );
        NormalDistributionParameters_exposer.def_readwrite( "mStandardDeviation", &alignlib::NormalDistributionParameters::mStandardDeviation );
    }

}
