// This file has been generated by Py++.

#ifndef PositionVector_hpp__pyplusplus_wrapper
#define PositionVector_hpp__pyplusplus_wrapper

void register_PositionVector_class();

#endif//PositionVector_hpp__pyplusplus_wrapper
