// This file has been generated by Py++.

#include "boost/python.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "ResiduePair.pypp.hpp"

namespace bp = boost::python;

void register_ResiduePair_class(){

    { //::alignlib::ResiduePair
        typedef bp::class_< alignlib::ResiduePair > ResiduePair_exposer_t;
        ResiduePair_exposer_t ResiduePair_exposer = ResiduePair_exposer_t( "ResiduePair" );
        bp::scope ResiduePair_scope( ResiduePair_exposer );
        { //::alignlib::ResiduePair::getDiagonal
        
            typedef ::alignlib::Position ( ::alignlib::ResiduePair::*getDiagonal_function_type )(  ) const;
            
            ResiduePair_exposer.def( 
                "getDiagonal"
                , getDiagonal_function_type( &::alignlib::ResiduePair::getDiagonal ) );
        
        }
        { //::alignlib::ResiduePair::operator=
        
            typedef ::alignlib::ResiduePair & ( ::alignlib::ResiduePair::*assign_function_type )( ::alignlib::ResiduePair const & ) ;
            
            ResiduePair_exposer.def( 
                "assign"
                , assign_function_type( &::alignlib::ResiduePair::operator= )
                , ( bp::arg("src") )
                , bp::return_self< >() );
        
        }
        ResiduePair_exposer.def_readwrite( "mCol", &alignlib::ResiduePair::mCol );
        ResiduePair_exposer.def_readwrite( "mRow", &alignlib::ResiduePair::mRow );
        ResiduePair_exposer.def_readwrite( "mScore", &alignlib::ResiduePair::mScore );
        ResiduePair_exposer.def( bp::self_ns::str( bp::self ) );
    }

}
