// This file has been generated by Py++.

#include "boost/python.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "Segment.pypp.hpp"

namespace bp = boost::python;

void register_Segment_class(){

    { //::alignlib::Segment
        typedef bp::class_< alignlib::Segment > Segment_exposer_t;
        Segment_exposer_t Segment_exposer = Segment_exposer_t( "Segment" );
        bp::scope Segment_scope( Segment_exposer );
        { //::alignlib::Segment::getSize
        
            typedef ::alignlib::Position ( ::alignlib::Segment::*getSize_function_type )(  ) const;
            
            Segment_exposer.def( 
                "getSize"
                , getSize_function_type( &::alignlib::Segment::getSize ) );
        
        }
        { //::alignlib::Segment::isEmpty
        
            typedef bool ( ::alignlib::Segment::*isEmpty_function_type )(  ) const;
            
            Segment_exposer.def( 
                "isEmpty"
                , isEmpty_function_type( &::alignlib::Segment::isEmpty ) );
        
        }
        Segment_exposer.def_readwrite( "mEnd", &alignlib::Segment::mEnd );
        Segment_exposer.def_readwrite( "mStart", &alignlib::Segment::mStart );
    }

}
