// This file has been generated by Py++.

#include "boost/python.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "Treetor.pypp.hpp"

namespace bp = boost::python;

void register_Treetor_class(){

    { //::alignlib::Treetor
        typedef bp::class_< alignlib::Treetor, boost::noncopyable > Treetor_exposer_t;
        Treetor_exposer_t Treetor_exposer = Treetor_exposer_t( "Treetor", bp::no_init );
        bp::scope Treetor_scope( Treetor_exposer );
        { //::alignlib::Treetor::calculateTree
        
            typedef void ( ::alignlib::Treetor::*calculateTree_function_type )( ::alignlib::HTree &,::alignlib::HMultipleAlignment const & ) const;
            
            Treetor_exposer.def( 
                "calculateTree"
                , calculateTree_function_type( &::alignlib::Treetor::calculateTree )
                , ( bp::arg("dest"), bp::arg("src") ) );
        
        }
        bp::register_ptr_to_python< boost::shared_ptr< alignlib::Treetor > >();
    }

}
