// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "vector_less__unsigned_char__greater_.pypp.hpp"

namespace bp = boost::python;

void register_vector_less__unsigned_char__greater__class(){

    bp::class_< std::vector< unsigned char > >("vector_less__unsigned_char__greater_")    
        .def( bp::vector_indexing_suite< ::std::vector< unsigned char >, true >() );

}
