// This file has been generated by Py++.

#include "boost/python.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "Weightor.pypp.hpp"

namespace bp = boost::python;

void register_Weightor_class(){

    { //::alignlib::Weightor
        typedef bp::class_< alignlib::Weightor, boost::noncopyable > Weightor_exposer_t;
        Weightor_exposer_t Weightor_exposer = Weightor_exposer_t( "Weightor", bp::no_init );
        bp::scope Weightor_scope( Weightor_exposer );
        { //::alignlib::Weightor::fillCounts
        
            typedef void ( ::alignlib::Weightor::*fillCounts_function_type )( ::alignlib::WeightedCountMatrix &,::alignlib::HMultipleAlignment const &,::alignlib::HEncoder const & ) const;
            
            Weightor_exposer.def( 
                "fillCounts"
                , fillCounts_function_type( &::alignlib::Weightor::fillCounts )
                , ( bp::arg("counts"), bp::arg("src"), bp::arg("translator") ) );
        
        }
        { //::alignlib::Weightor::getClone
        
            typedef ::alignlib::HWeightor ( ::alignlib::Weightor::*getClone_function_type )(  ) const;
            
            Weightor_exposer.def( 
                "getClone"
                , getClone_function_type( &::alignlib::Weightor::getClone ) );
        
        }
        { //::alignlib::Weightor::getNew
        
            typedef ::alignlib::HWeightor ( ::alignlib::Weightor::*getNew_function_type )(  ) const;
            
            Weightor_exposer.def( 
                "getNew"
                , getNew_function_type( &::alignlib::Weightor::getNew ) );
        
        }
        bp::register_ptr_to_python< boost::shared_ptr< alignlib::Weightor > >();
    }

}
